extends SceneTree
## Deterministic production-logic milestone checks, extended as milestones land.

const Needs := preload("res://scripts/need_system.gd")
const Economy := preload("res://scripts/economy_system.gd")
const Planner := preload("res://scripts/civilization_planner.gd")
const Resources := preload("res://scripts/resource_system.gd")
const Salvage := preload("res://scripts/salvage_system.gd")
var failed := false

func _initialize() -> void:
	call_deferred("_run")

func check(condition: bool, message: String) -> void:
	if not condition:
		failed = true
		push_error("POC4_FAST_FAIL: " + message)
		quit(1)

func _run() -> void:
	var needs := Needs.new()
	for kind in ["chair", "table", "box"]:
		var profile := Resources.derive({"kind": kind, "dimensions": [20, 20, 20]})
		check(profile.harvestable and profile.protected and profile.stages.size() == 4, "generic furniture derivation: " + kind)
	check(not Resources.derive({"kind": "plant"}).harvestable, "unknown/non-material object conservative")
	check(not Resources.validate_profile({"contents": {"gold": 1}}).is_empty(), "profile validation rejects unsupported resources")
	check(not Resources.validate_profile({"stages": [{"name": "EMPTY", "work": 1, "yields": {}}]}).is_empty(), "empty salvage stage rejected")
	var salvage := Salvage.new()
	salvage.configure({"item": {"profile": Resources.derive({"kind": "chair", "dimensions": [20, 20, 20]})}})
	check(salvage.work("item", 0, 100, Vector3.ZERO, Vector3.ZERO).is_empty(), "protected object produces nothing")
	check(salvage.authorize("item") and salvage.work("item", 0, 100, Vector3(9, 0, 0), Vector3.ZERO).is_empty(), "real on-site work required")
	for stage in range(4):
		check(not salvage.work("item", stage, 100, Vector3.ZERO, Vector3.ZERO).is_empty(), "stage completion yields")
		check(salvage.work("item", stage, 100, Vector3.ZERO, Vector3.ZERO).is_empty(), "completed stage never yields twice")
	check(salvage.depleted("item") and not salvage.authorize("item"), "depleted authorization rejected")
	var resources := Resources.new()
	resources.configure({"objects": [{"id": "cache", "kind": "food_cache", "position": [0, 0, 0], "resource_profile": {"contents": {"food": 2}}}]})
	check(resources.reserve_source("cache", "food", 2) and not resources.reserve_source("cache", "food", 1), "source reserves exclusive finite contents")
	var bundle := resources.extract("cache", "food", 2, Vector3.ZERO)
	check(bundle > 0 and resources.source_available("cache", "food") == 0 and resources.extract("cache", "food", 2, Vector3.ZERO) == -1, "source depletion persists")
	check(resources.reserve_bundle(bundle, 1) and not resources.pickup_bundle(bundle, 2, Vector3.ZERO), "bundle ownership")
	check(resources.pickup_bundle(bundle, 1, Vector3.ZERO), "bundle pickup")
	var planner := Planner.new()
	check(planner.set_priority("Exploration", 4) and planner.score("FLOOR_PATROL", 0, 0) > planner.score("CONSTRUCTION_BUILD", 0, 0), "priority changes work ranking")
	planner.set_priority("Exploration", 0)
	check(planner.score("FLOOR_PATROL", 0, 0) == -INF, "disabled optional task family")
	check(planner.secure("water") and not planner.secure("gold") and planner.authorized.is_empty(), "directives do not authorize destruction")
	var state := needs.initial(0)
	needs.decay(state, 100)
	check(float(state.water) > float(state.food), "water becomes urgent before food")
	state.fatigue = 0.9
	needs.decay(state, 20, true)
	check(float(state.fatigue) < 0.5, "rest recovers fatigue")
	state.water = 1.0
	check(needs.work_factor(state) == 0.25, "critical need limits work")
	var economy := Economy.new()
	economy.configure({"food": 100, "water": 150, "wood": 4, "metal": 4})
	check(economy.forecast("water", 50) == 1, "forecast uses population demand")
	var first := economy.reserve("wood", 4, "project")
	check(first > 0 and economy.reserve("wood", 1, "other") == -1, "reservations prevent double spend")
	check(economy.pickup(first) and not economy.pickup(first), "pickup is exclusive")
	check(economy.deliver(first) and economy.consume(first, true), "delivered material consumption")
	check(economy.audit().is_empty(), "stock conservation")
	check(not resources.deliver_bundle(bundle, 1, Vector3(10, 0, 0), Vector3.ZERO, economy) and resources.deliver_bundle(bundle, 1, Vector3.ZERO, Vector3.ZERO, economy), "bundle requires real delivery")
	check(not resources.deliver_bundle(bundle, 1, Vector3.ZERO, Vector3.ZERO, economy) and resources.audit().is_empty(), "delivered bundle cannot duplicate")
	var ration := economy.reserve("food", 1, "cancelled-care")
	economy.release(ration)
	check(economy.available.food == 102 and economy.tickets.is_empty(), "cancellation releases reservation")
	var cancelled := economy.reserve("metal", 1, "traversal")
	economy.pickup(cancelled)
	var dropped := economy.drop(cancelled)
	check(dropped.amount == 1 and economy.available.metal == 3 and economy.audit().is_empty(), "carried cancellation exports material without restoring depot stock")
	var scene := (load("res://scenes/pipeline_proof.tscn") as PackedScene).instantiate()
	root.add_child(scene)
	await process_frame
	var simulation: Node = scene.start_civilization({"stock": {"food": 5000, "water": 5000}, "shelter_capacity": 44, "rest_capacity": 12})
	simulation.set_process(false)
	for tick in range(12000): simulation.step()
	var status: Dictionary = simulation.status()
	check(status.population == 50 and status.meals > 50 and status.drinks > 50 and status.rests >= 50, "fifty citizens eat/drink/rest autonomously")
	check(simulation.self_care_completed.size() == 50, "every citizen participates")
	check(not simulation.citizens[49].needs.sheltered and simulation.citizens[0].needs.sheltered, "finite shelter")
	check(simulation.economy.audit().is_empty(), "production consumption conservation")
	check(simulation.coordinator.tasks.size() <= 600, "bounded shared tasks")
	simulation.hud.refresh()
	check(simulation.hud.resources.text.contains("use 150/day") and simulation.hud.strategy.text.contains("Shelter shortage"), "normal UI uses demand and shelter state")
	check(simulation.hud.get_node("Directives").text.contains("Traversal:"), "normal strategic HUD shows project state")
	scene.set("_selected_citizen", simulation.citizens[49])
	simulation.hud.refresh()
	check(simulation.hud.citizen_label.text.contains("Fatigue:") and simulation.hud.citizen_label.text.contains("Shelter: shortage"), "normal citizen inspection reads real needs and shelter")
	simulation.planner.set_priority("Exploration", 0)
	simulation.hud.refresh()
	check(simulation.hud.priority_choices.Exploration.selected == 0, "HUD priority reflects authoritative settings")
	var before: int = simulation.planner.labor.get("Exploration", 0)
	for tick in range(2000): simulation.step()
	check(int(simulation.planner.labor.get("Exploration", 0)) == before, "production disabled exploration assigns no new optional labor")
	check(simulation.salvage.objects.chair.stage == 0 and simulation.resources.generated.wood == 0, "production protected object remains intact")
	check(simulation.authorize_salvage("chair"), "civilization salvage directive")
	for tick in range(3000): simulation.step()
	check(simulation.salvage.depleted("chair") and simulation.salvage.stage_completions == 4, "production multiple salvage stages")
	check(simulation.haul_pickups >= 4 and simulation.haul_deliveries >= 4 and simulation.economy.available.wood > 0 and simulation.economy.available.metal == 4, "citizens actually haul salvage yield")
	check(not scene.get_node("RoomObjects/chair").visible and not simulation.coordinator.navigation.is_obstacle_position(Vector3(-58, 0, -20)), "visible depletion removes floor obstacle")
	check(simulation.resources.audit().is_empty() and simulation.economy.audit().is_empty(), "salvage/haul conservation")
	var clock_before: float = simulation.seconds
	simulation.speed = 0
	simulation._process(10)
	check(simulation.seconds == clock_before, "pause freezes production state")
	simulation.speed = 4
	simulation._process(0.25)
	check(is_equal_approx(simulation.seconds, clock_before + 1), "4x advances fixed simulation seconds")
	simulation.speed = 10
	simulation._process(0.1)
	check(is_equal_approx(simulation.seconds, clock_before + 2), "10x advances fixed simulation seconds")
	if failed: return
	print("POC4_M1_PASS " + JSON.stringify(status))
	print("POC4_M2_PASS accounting=conserved reservation=exclusive forecast=population_based normal_ui=verified")
	print("POC4_M3_PASS priority_ranking=verified production_labor=verified directives=validated")
	print("POC4_M4_PASS generic_profiles=chair_table_box contract=standard_room_definition invalid_metadata=rejected")
	print("POC4_M5_PASS protected=verified stages=4 real_work=verified pickups=%d deliveries=%d geometry=altered navigation=updated conservation=verified" % [simulation.haul_pickups, simulation.haul_deliveries])
	print("POC4_SPEED_PASS pause=true 4x=true 10x=true fixed_step=0.1")
	print("POC4_FAST_PASS")
	scene.queue_free()
	await process_frame
	quit()
