extends Node
## Verdant presentation adapter for dynamically constructed settlement modules.
##
## The production settlement-development system remains civilization-neutral and
## authoritative for placement, material delivery, build progress, capacity,
## navigation footprints, and completion. This adapter only changes presentation
## after those real modules are rendered.

var _refresh_timer := 0.0
var _active := false


func _ready() -> void:
	_active = OS.get_environment("ROOMSCALE_CIVILIZATION").strip_edges().to_lower() == "verdant"


func _process(delta: float) -> void:
	if not _active:
		return
	_refresh_timer += delta
	if _refresh_timer < 0.2:
		return
	_refresh_timer = 0.0
	var scene := get_tree().current_scene as Node3D
	if scene == null:
		return
	for child in scene.get_children():
		if child is Node3D and child.has_meta("module") and child.has_meta("stage"):
			_style_module(child as Node3D)


func _style_module(root: Node3D) -> void:
	var stage := String(root.get_meta("stage", ""))
	var kind := String(root.get_meta("module", ""))
	var signature := "%s:%s" % [kind, stage]
	if String(root.get_meta("verdant_signature", "")) == signature:
		return
	root.set_meta("verdant_signature", signature)
	_recolor_existing(root)
	var overlay := root.get_node_or_null("VerdantGrowth") as Node3D
	if overlay != null:
		root.remove_child(overlay)
		overlay.free()
	overlay = Node3D.new()
	overlay.name = "VerdantGrowth"
	root.add_child(overlay)
	_build_stage_growth(overlay, kind, stage)
	_hide_replaced_structure(root)


func _hide_replaced_structure(root: Node3D) -> void:
	# Keep the production footprint and assembly pin. All replacement forms are
	# visual children of that same earned module; no placement or capacity changes.
	# Duplicate production mesh names may be generated by Godot, so identify the
	# ground pieces geometrically instead of relying on their display names.
	for child in root.get_children():
		if not (child is MeshInstance3D) or child.name == "AssemblyWorkpiece":
			continue
		var mesh := child as MeshInstance3D
		var is_ground_piece := mesh.mesh != null and mesh.position.y <= 0.09 and mesh.mesh.get_aabb().size.y <= 0.11
		mesh.visible = is_ground_piece


func _recolor_existing(root: Node3D) -> void:
	for child in root.get_children():
		if not (child is MeshInstance3D):
			continue
		var mesh := child as MeshInstance3D
		var name := String(mesh.name).to_lower()
		var color := Color("6b5339")
		if "roof" in name or "panel" in name or "back" in name or "side" in name:
			color = Color("516f3e")
		elif "window" in name:
			color = Color("d8cf72")
		elif "stone" in name or "foundation" in name or "yard" in name or "threshold" in name:
			color = Color("776f57")
		elif "door" in name:
			color = Color("58432f")
		elif "workpiece" in name:
			color = Color("7c8c4b")
		mesh.material_override = _material(color, 0.94)


func _build_stage_growth(root: Node3D, kind: String, stage: String) -> void:
	# Each production re-render creates a new module root, so these details track
	# the real construction stage without inventing a second build progression.
	for index in range(5):
		var angle := TAU * float(index) / 5.0
		var radius := 3.2 + float(index % 2) * 0.6
		var start := Vector3(cos(angle) * 0.8, 0.05, sin(angle) * 0.8 - 1.0)
		var finish := Vector3(cos(angle) * radius, 0.09, sin(angle) * radius - 1.0)
		_segment(root, "FoundationRoot%d" % index, start, finish, 0.065, Color("58452f"))
		_sphere(root, "RootMoss%d" % index, finish + Vector3(0, -0.04, 0), Vector3(0.9, 0.09, 0.65), Color("4d763e"))
	if stage == "FOUNDATION":
		return
	var height := 1.8 if kind == "housing" else 1.05
	for index in range(4):
		var x := -3.8 + float(index) * 2.53
		var points := [Vector3(x, 0.08, -2.85), Vector3(x - 0.12, height * 0.72, -2.35), Vector3(x, height, -1.0), Vector3(x + 0.12, height * 0.72, 0.35), Vector3(x, 0.08, 0.85)]
		for piece in range(1, points.size()):
			_segment(root, "TwigArch%d_%d" % [index, piece], points[piece - 1], points[piece], 0.075, Color("665039"))
		_leaf(root, "PostLeaf%d" % index, Vector3(x - 0.12, height * 0.65, -2.35), Vector3(0.55, 0.045, 0.24), Color("658a47"), float(index) * 0.8)
	if kind == "workshop":
		_build_nursery_tree(root, stage)
	if stage == "FRAME":
		return
	if kind == "housing":
		for index in range(3):
			var x := -2.7 + index * 2.7
			_sphere(root, "HomePod%d" % index, Vector3(x, 0.98, -1.0), Vector3(2.35, 1.8, 2.35), Color("71804d") if index % 2 == 0 else Color("8b724b"))
	else:
		# Low woven walls leave the front open so workers and stored supplies read.
		_sphere(root, "WovenBack", Vector3(0, 0.48, -2.82), Vector3(7.8, 0.82, 0.25), Color("806743"))
		for side in [-1.0, 1.0]:
			_sphere(root, "WovenSide%s" % side, Vector3(side * 3.8, 0.45, -1.0), Vector3(0.22, 0.75, 3.6), Color("6b573a"))
	for index in range(6):
		var x := -3.6 + float(index) * 1.45
		_leaf(root, "WallLeaf%d" % index, Vector3(x, 0.7, -2.7), Vector3(0.65, 0.055, 0.28), Color("547a40") if index % 2 == 0 else Color("6a914b"), float(index) * 0.55)
	if stage == "SHELL":
		return
	var label := "GROVE SHELTER"
	match kind:
		"depot": label = "SEED CACHE"
		"housing": label = "POD HOMES"
		"workshop": label = "GROWTH NURSERY"
	_world_label(root, "VerdantModuleLabel", label, Vector3(0, 2.8 if kind == "workshop" else height + 0.5, -0.9), Color("d8cf72"))
	if kind in ["shelter", "depot"]:
		for index in range(3):
			var canopy := _leaf(root, "GrownCanopy%d" % index, Vector3(-2.6 + index * 2.6, height + 0.13, -1.0), Vector3(3.1, 0.42, 4.5), Color("50783e") if index % 2 == 0 else Color("6c8e49"), 0.08 * (index - 1))
			canopy.rotation.z = 0.025 * (index - 1)
			_segment(root, "RoofBranch%d" % index, Vector3(-3.8 + index * 2.6, 0.72, -2.3), Vector3(-2.6 + index * 2.6, 1.3, -0.9), 0.08, Color("80623e"))
	if kind == "shelter":
		for index in range(5):
			_sphere(root, "SleepMoss%d" % index, Vector3(-2.8 + index * 1.4, 0.13, -1.0), Vector3(0.65, 0.12, 0.9), Color("4d763e"))
	elif kind == "depot":
		for index in range(3):
			_sphere(root, "StoragePod%d" % index, Vector3(-2.5 + index * 2.5, 0.47, -1.0), Vector3(1.45, 0.9, 1.15), Color("9a7742"))
			_leaf(root, "PodLid%d" % index, Vector3(-2.5 + index * 2.5, 0.95, -1.0), Vector3(1.5, 0.09, 0.8), Color("6c8544"), 0.3 * index)
			_magic_bloom(root, "SeedBloom%d" % index, Vector3(-2.5 + index * 2.5, 0.74, -0.48), 0.07)
	elif kind == "housing":
		for index in range(3):
			var x := -2.7 + index * 2.7
			_leaf(root, "HomeCanopy%d" % index, Vector3(x, 1.91, -1.0), Vector3(2.65, 0.16, 1.7), Color("50783e"), -0.12 + index * 0.12)
			_sphere(root, "PodDoor%d" % index, Vector3(x, 0.45, 0.1), Vector3(0.39, 0.7, 0.18), Color("3b472d"))
			for side in [-1.0, 1.0]:
				_segment(root, "HomeBranch%d_%s" % [index, side], Vector3(x + side * 0.9, 0.09, -0.7), Vector3(x + side * 0.8, 1.45, -0.9), 0.05, Color("70543a"))
				_segment(root, "CanopyBranch%d_%s" % [index, side], Vector3(x + side * 0.8, 1.45, -0.9), Vector3(x + side * 0.35, 1.92, -1.0), 0.04, Color("70543a"))
			_magic_bloom(root, "PodLantern%d" % index, Vector3(x + 0.35, 0.62, 0.12), 0.09)
	elif kind == "workshop":
		for index in range(3):
			_sphere(root, "NurserySeed%d" % index, Vector3(-2.5 + index * 1.5, 0.28, -1.0), Vector3(0.55, 0.48, 0.55), Color("af9654"))
	for index in range(3):
		var at := Vector3(-3.4 + index * 3.3, 0, 1.7)
		_cylinder(root, "FungusStem%d" % index, 0.035, 0.2, at + Vector3.UP * 0.1, Color("d7c7a0"))
		_sphere(root, "FungusCap%d" % index, at + Vector3.UP * 0.23, Vector3(0.32, 0.1, 0.32), Color("b77a58"))
	for side in [-1.0, 1.0]:
		var at := Vector3(side * 3.2, 0.09, 0.75)
		_segment(root, "BloomStem%s" % side, at, at + Vector3.UP * 0.28, 0.025, Color("628248"))
		_magic_bloom(root, "GroveBloom%s" % side, at + Vector3.UP * 0.28, 0.1)


func _build_nursery_tree(root: Node3D, stage: String) -> void:
	# Branch length and buds follow only the real module stage. This is the
	# workshop's visual replacement, never a source of materials or capability.
	var growth := 0.55 if stage == "FRAME" else (0.8 if stage == "SHELL" else 1.0)
	var base := Vector3(0, 0.08, -1.8)
	var fork := Vector3(-0.22, 0.85 * growth, -1.75)
	var top := Vector3(0.12, 1.8 * growth, -1.7)
	_segment(root, "NurseryTrunk", base, fork, 0.15, Color("795738"))
	_segment(root, "NurseryLeader", fork, top, 0.10, Color("795738"))
	_sphere(root, "NurseryKnot", fork, Vector3(0.34, 0.3, 0.32), Color("795738"))
	for side in [-1.0, 1.0]:
		var tip := Vector3(side * 2.25 * growth, 1.4 * growth, -1.25)
		_segment(root, "NurseryFork%s" % side, fork, tip, 0.075, Color("81603e"))
		if stage != "FRAME":
			_sphere(root, "NurseryCrown%s" % side, tip + Vector3.UP * 0.18, Vector3(2.8, 0.8, 2.25) * growth, Color("567d40") if side < 0 else Color("7a984e"))
			_leaf(root, "NurseryShoot%s" % side, tip + Vector3(0, 0.57, 0.1), Vector3(1.3, 0.12, 0.65) * growth, Color("8fae60"), side * 0.7)
		if stage == "COMPLETE":
			_magic_bloom(root, "NurseryMagic%s" % side, tip + Vector3(0, 0.55, 0.8), 0.19)
	if stage == "COMPLETE":
		_sphere(root, "NurseryHighCrown", top + Vector3.UP * 0.12, Vector3(2.7, 0.75, 2.1), Color("5e8845"))
		_magic_bloom(root, "NurseryTopBloom", top + Vector3.UP * 0.52, 0.22)


func _magic_bloom(parent: Node3D, node_name: String, at: Vector3, radius: float) -> void:
	var bloom := Node3D.new()
	bloom.name = node_name
	bloom.position = at
	parent.add_child(bloom)
	for petal in range(5):
		var angle := TAU * float(petal) / 5.0
		_leaf(bloom, "Petal%d" % petal, Vector3(cos(angle) * radius, 0, sin(angle) * radius), Vector3(radius * 1.65, radius * 0.25, radius * 0.8), Color("c59ed2") if petal % 2 == 0 else Color("dac982"), angle)
	var heart := _sphere(bloom, "GlowHeart", Vector3(0, radius * 0.15, 0), Vector3.ONE * radius * 0.65, Color("e4edaf"))
	var material := heart.material_override as StandardMaterial3D
	material.emission_enabled = true
	material.emission = Color("ddec99")
	material.emission_energy_multiplier = 0.65


func _material(color: Color, roughness: float) -> StandardMaterial3D:
	var material := StandardMaterial3D.new()
	material.albedo_color = color
	material.roughness = roughness
	return material


func _sphere(parent: Node3D, node_name: String, at: Vector3, scale_value: Vector3, color: Color) -> MeshInstance3D:
	var item := MeshInstance3D.new()
	item.name = node_name
	var mesh := SphereMesh.new()
	mesh.radius = 0.5
	mesh.height = 1.0
	mesh.radial_segments = 12
	mesh.rings = 6
	item.mesh = mesh
	item.position = at
	item.scale = scale_value
	item.material_override = _material(color, 0.95)
	parent.add_child(item)
	return item


func _cylinder(parent: Node3D, node_name: String, radius: float, height: float, at: Vector3, color: Color) -> MeshInstance3D:
	var item := MeshInstance3D.new()
	item.name = node_name
	var mesh := CylinderMesh.new()
	mesh.top_radius = radius
	mesh.bottom_radius = radius
	mesh.height = height
	mesh.radial_segments = 12
	item.mesh = mesh
	item.position = at
	item.material_override = _material(color, 0.95)
	parent.add_child(item)
	return item


func _segment(parent: Node3D, node_name: String, start: Vector3, finish: Vector3, radius: float, color: Color) -> MeshInstance3D:
	var direction := finish - start
	var item := _cylinder(parent, node_name, radius, maxf(direction.length(), 0.001), (start + finish) * 0.5, color)
	if direction.length() > 0.0001:
		item.quaternion = Quaternion(Vector3.UP, direction.normalized())
	return item


func _leaf(parent: Node3D, node_name: String, at: Vector3, size: Vector3, color: Color, yaw: float) -> MeshInstance3D:
	var leaf := _sphere(parent, node_name, at, size, color)
	leaf.rotation.y = yaw
	leaf.rotation.z = 0.12
	return leaf


func _world_label(parent: Node3D, node_name: String, value: String, at: Vector3, color: Color) -> Label3D:
	var label := Label3D.new()
	label.name = node_name
	label.text = value
	label.position = at
	label.font_size = 18
	label.pixel_size = 0.014
	label.billboard = BaseMaterial3D.BILLBOARD_ENABLED
	label.modulate = color
	label.outline_modulate = Color("263320")
	label.outline_size = 3
	parent.add_child(label)
	return label
